name: sf_python
channels:
  - defaults
dependencies:
  - python=3.10.12
  - pandas=1.5.3
  - numpy=1.23.5
  - scipy=1.11.3
  - pip=22.3.1
  - matplotlib=3.8.2
  - pytorch=2.2.0
  - nilearn=0.10.2
  - pip:
    - plotly==5.15.0
    - kaleido==0.2.1
    - neuroquery==1.0.4
    - nibabel==5.2.0
    - scikit-learn==1.3.2